[build]
  publish = "dist"
  command = "npm run generate"

[context.production]
  command = "npm run generate"
  [context.production.environment]
    HOST = "127.0.0.1"
    PORT = "80"
    WEBSITE_NAME = "Gentry Way Co., Ltd."
    WEBSITE_DESC = "Gentry Way Product Catalog Website"
